#nombre
name: "Deploy CodigoFacilito"
#Trigger
on:
  push:
    branches: ["main"]
#Jobs 
jobs:
  deploy-codigofacilito:
  # runner donde se va a ejecutar
  runs-on: ubuntu-latest

  # pasos que va ajecutar
  step:
    run: echo "Hacemos pull de código"
    run: echo "Correr migraciones"
    run: echo "Generar binario"
    run: echo "Publicar versión"